# ==================================
#       CONTROLLER MANAGER
# ==================================

# the weird /**/ before each of these is a wildcard for any namespace.

/uirover/control/controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    arm_position_controller:
      type: position_controllers/JointGroupPositionController

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# ==================================
#           CONTROLLERS
# ==================================
/uirover/control/joint_state_broadcaster:
  ros__parameters:
    joints:
      - arm_j0
      - arm_j1
      - arm_j2
      - arm_j3
      - arm_j4
      - arm_j5
      - fl_wheel_joint
      - fr_wheel_joint
      - ml_wheel_joint
      - mr_wheel_joint
      - bl_wheel_joint
      - br_wheel_joint

/uirover/control/diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["fl_wheel_joint", "ml_wheel_joint", "bl_wheel_joint"]
    right_wheel_names: ["fr_wheel_joint", "mr_wheel_joint", "br_wheel_joint"]

    wheel_separation: 0.7493
    wheels_per_side: 3
    wheel_radius: 0.01143

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    position_feedback: false
    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5 # seconds
    # publish_limited_velocity: false
    # velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.max_velocity: .NAN
    linear.x.max_acceleration: .NAN
    linear.x.max_jerk: .NAN

    angular.z.max_velocity: .NAN
    angular.z.max_acceleration: .NAN
    angular.z.max_jerk: .NAN

# Used when performing path planning operations
/uirover/control/arm_trajectory_controller:
  ros__parameters:
    joints:
      - arm_j0
      - arm_j1
      - arm_j2
      - arm_j3
      - arm_j4
      - arm_j5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
  
# used when directly teleoperating arm
/uirover/control/arm_position_controller:
  ros__parameters:
    joints:
      - arm_j0
      - arm_j1
      - arm_j2
      - arm_j3
      - arm_j4
      - arm_j5