# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - /uirover/control/arm_trajectory_controller
    - end_effector

  /uirover/control/arm_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - arm_j0
      - arm_j1
      - arm_j2
      - arm_j3
      - arm_j4
      - arm_j5
    action_ns: follow_joint_trajectory
    default: true
  end_effector:
    type: GripperCommand
    joints:
      - end_effector
    action_ns: gripper_cmd
    default: true